---
title: "R Notebook"
output: html_notebook
---

Matrisler
```{r}
v1 <- c(3,4,6,8,5)
v2 <- c(4,8,4,7,1)
v3 <- c(2,2,5,4,6)
v4 <- c(4,7,5,2,5)

# column bazında birleştirme ile matris oluşturduk
matris <- cbind(v1, v2, v3, v4)
matris

is.matrix(matris)

matrix(nrow = 3, ncol = 3, 1:9)

matrix(1:4, 2, 2)

# byrow = True argümanı verileri öncelikle satırlara göre yerleştirir
matrix(1:9, nrow = 3, ncol = 3, byrow = TRUE)

matrix(c(1,2,3,11,22,33), nrow = 2, ncol = 3, byrow = TRUE)


matrix(c(1,2,11,22,111,222,1111,2222), 
       nrow = 4, 
       ncol = 2, 
       byrow = TRUE,
       # aşağıda matrisin column ve row'larını biçimlendirdik
       dimnames = list(c("rakam","onluk","yuzluk","binlik"), c("bir", "iki")))


m <- matrix(c(1,2,11,22,111,222,1111,2222), 
       nrow = 4, 
       ncol = 2, 
       byrow = TRUE,
       dimnames = list(c("rakam","onluk","yuzluk","binlik"), c("bir", "iki")))
# m'nin kaça kaç bir matris olduğunu buluyoruz
dim(m)


MA <- rnorm(16, 0, 1)
MA <- matrix(MA, nrow = 4, ncol = 4)

MB <- rnorm(16, 90, 10)
MB <- matrix(MB, nrow = 4, ncol = 4)

# satır bazında birleştirme
rbind(MA,MB)

#sütun bazında birleştirme
cbind(MA, MB)


m <- matrix(c(1,2,11,22,111,222,1111,2222), 
       nrow = 4, 
       ncol = 2, 
       byrow = TRUE)
m

# dimnames parametresiyle aynı işi yapar
colnames(m) <- c("bir","iki")
rownames(m) <- c("rakam", "onlar", "yuzler", "binler")
m

# satır ve sütun isimlerini çekeriz
colnames(m)
rownames(m)

# matrisin indexlerine erişme
m[1,1]
m[4,1]

# matrisin satır ve sütunlarına erişme
#sütun
m[,2]
#satır
m[1,]
m[3,]

```

Matris Elemanlarina Erismek
```{r}
m
m[1,1]
m[4,2]
m[,2]
```





